name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurer Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Construire et taguer l'image
      - name: Build and Tag Docker Image
        run: |
          docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/client_api:latest

      # Pousser l'image sur Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/client_api:latest
